
---
title: "Final Project"
author:
- address: University of Oregon, Eugene, OR
  affiliation: '1'
  corresponding: yes
  email: my@uoregon.edu
  name: Teresa Chen
- affiliation: '2'
  name: Steffi Huang
- affiliation: '2'
  name: Jun Lan
- affiliation: '3'
  name: Ting-fen Lin
affiliation:
- id: '1'
  institution: Human Physiology
- id: '2'
  institution: East Asia Languages & Literatures
- id: '3'
  institution: Communication Disorders & Sciences
authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.
  Enter author note here.
bibliography: r-references.bib
classoption: man, fleqn, noextraspace
documentclass: apa6
draft: no
figurelist: no
floatsintext: no
footnotelist: no
keywords: keywords
linenumbers: yes
mask: no
shorttitle: EDLD 610
tablelist: no
abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  One or two sentences to put the results into a more **general context**.
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  <!-- https://tinyurl.com/ybremelq -->
wordcount: X
---
output: 
  html_document:
    toc: true
    toc_depth: true
    code_folding: "hide"
---
---

```{r setup, eval = TRUE, message = FALSE, warning = FALSE, echo = FALSE, fig.width = 6.5, fig.height = 6.5}
knitr::opts_chunk$set(error = TRUE)
```


```{r load-tidyverse, message = FALSE, warning = FALSE, include = FALSE}
library(dplyr)
library(tidyverse)
library(here)
library(rio)
library(papaja)
list.files(here("data"))
here()
d <- import(here("data", "voweldata.xlsx"),
              setclass = "tbl_df") %>% 
  characterize()
```





```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Introduction
blah blah blah

# Methods
blah blah blah

## Participants
blah blah blah

## Material
blah blah blah

## Procedure
blah blah blah

## Data analysis
blah blah blah

# Results
blah blah blah

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
